// <auto-generated />
namespace Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edycjanotnullwmodeluzamówienie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edycjanotnullwmodeluzamówienie));
        
        string IMigrationMetadata.Id
        {
            get { return "201708050846087_edycja  not null w modelu zamówienie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
