// <auto-generated />
namespace Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edycjamodelikluczy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edycjamodelikluczy));
        
        string IMigrationMetadata.Id
        {
            get { return "201708050757127_edycja modeli  kluczy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
