// <auto-generated />
namespace Rental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edycjanotnullwmodeluzamówieniev2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edycjanotnullwmodeluzamówieniev2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708050850040_edycja  not null w modelu zamówieniev2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
